In [1]:
from jupyter_dash import JupyterDash
from dash import dcc, html, Input, Output
import yfinance as yf  
import plotly.express as px
import pandas as pd

In [2]:
df = pd.read_csv("rotten_tomatoes_top_movies_2019-01-15.csv")

In [3]:
df[df['Genres']=='action|adventure']

,Rank,Title,RatingTomatometer,No. of Reviews,Genres
0,1,Black Panther (2018),97,444,action|adventure
1,2,Mad Max: Fury Road (2015),97,394,action|adventure
2,3,Wonder Woman (2017),93,410,action|adventure
3,4,Metropolis (1927),99,118,action|adventure
4,5,Coco (2017),97,308,action|adventure
...,...,...,...,...,...
95,96,From Russia With Love (1964),96,55,action|adventure
96,97,Superman (1978),94,65,action|adventure
97,98,Saving Private Ryan (1998),93,137,action|adventure
98,99,The Lord of the Rings: The Return of the King ...,93,270,action|adventure
99,100,Embrace Of The Serpent (El Abrazo De La Serpie...,96,139,action|adventure

In [3]:
app = JupyterDash(__name__)

/Users/206697387/miniconda3/envs/corp_comm/lib/python3.12/site-packages/dash/dash.py:556: UserWarning:

JupyterDash is deprecated, use Dash instead.
See https://dash.plotly.com/dash-in-jupyter for more details.

In [5]:

app.layout = html.Div(children = [
    html.Div([
        html.H1("Rotten Tomatoes Movie Rankings"),
         
        html.Label("Select Genres:"),
        dcc.Dropdown(
            id='genres-selector',
            options=[
                {'label': 'action|adventure', 'value': 'action|adventure'},
                {'label': 'animation', 'value': 'animation'},
                {'label': 'art_house|international', 'value': 'art_house|international'},
                {'label': 'classics', 'value': 'classics'},
                {'label': 'comedy', 'value': 'comedy'},
                {'label': 'documentary', 'value': 'documentary'},
                {'label': 'drama', 'value': 'drama'},
                {'label': 'horror', 'value': 'horror'},
                {'label': 'kids|family', 'value': 'kids|family'},
                {'label': 'musical|performing_arts', 'value': 'musical|performing_arts'},
                {'label': 'mystery|suspense', 'value': 'mystery|suspense'},
                {'label': 'romance', 'value': 'romance'},
                {'label': 'science_fiction|fantasy', 'value': 'science_fiction|fantasy'},
                {'label': 'special_interest', 'value': 'special_interest'},
                {'label': 'sports|fitness', 'value': 'sports|fitness'},
                {'label': 'television', 'value': 'television'},
                {'label': 'western', 'value': 'western'},
            ],
            value='action|adventure'
        ),
         
        dcc.Graph(id='movie-genre-chart'),
    ]),
    html.Div([
        html.H1("Rotten Tomatoes- Count of Movie Reviews"),
        dcc.Graph(id='movie-reviews-chart'),
    ])
])

In [6]:
@app.callback(
    Output('movie-genre-chart', 'figure'),
    [Input('genres-selector', 'value')]
)
def update_chart(selected_genre):
    data = df[df['Genres']==selected_genre].head(20)
    fig = px.bar(data, x = "Title", y = "RatingTomatometer", title=f'{selected_genre} Movie Rankings')

    return fig

@app.callback(
    Output('movie-reviews-chart', 'figure'),
    [Input('genres-selector', 'value')]
)
def update_second_chart(selected_genre):
    data = df[df['Genres']==selected_genre].head(20)
    fig = px.bar(data, x = "Title", y = "No. of Reviews", title=f'{selected_genre} Number of Reviews')

    return fig

In [7]:
el= df[df['Genres']=='animation'].head(20)

In [8]:
el

,Rank,Title,RatingTomatometer,No. of Reviews,Genres
100,1,Inside Out (2015),98,347,animation
101,2,Coco (2017),97,308,animation
102,3,Paddington 2 (2018),100,216,animation
103,4,Incredibles 2 (2018),94,332,animation
104,5,Snow White and the Seven Dwarfs (1937),98,47,animation
105,6,Toy Story 2 (1999),100,163,animation
106,7,Zootopia (2016),97,268,animation
107,8,Up (2009),98,290,animation
108,9,Toy Story 3 (2010),98,299,animation
109,10,Finding Nemo (2003),99,262,animation
110,11,Pinocchio (1940),100,47,animation
111,12,Finding Dory (2016),94,309,animation
112,13,Toy Story (1995),100,81,animation
113,14,The LEGO Movie (2014),96,240,animation
114,15,WALL-E (2008),96,252,animation
115,16,Moana (2016),95,261,animation
116,17,Kubo and the Two Strings (2016),97,207,animation
117,18,Shaun the Sheep Movie (2015),99,160,animation
118,19,Ratatouille (2007),96,246,animation
119,20,Only Yesterday (1991),100,53,animation

In [7]:
if __name__ == '__main__':
    app.run_server(port=8060, mode='external')

Dash app running on http://127.0.0.1:8060/